version: '3.12'

services:
    react-nginx-app:

      stdin_open: true
      # 容器名称
      container_name: react-nginx-app-container
      build:
        # Dockerfile 所在目录
        context: .
        # Dockerfile 文件名称
        dockerfile: Dockerfile
      # 宿主机上的 4000 端口会映射到容器内的 80 端口
      ports:
        - 4000:80
      # 将 react-nginx-app 服务的目录（.）下的文件 挂载到容器工作目录 /usr/src/app 下
      # 这样可以在宿主机修改代码后，容器内会同步更新
      volumes: 
        - .:/usr/app
        
      # 使用的镜像名称
      image: krismile98/react-nginx-app:latest